name: Build and test
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./gradlew gem
    - run: mkdir .embulk
    - name: Download JRuby
      run: curl https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.jar -o jruby-complete-9.1.17.0.jar
    - name: Create embulk.properties
      run: echo "jruby=file://${PWD}/jruby-complete-9.1.17.0.jar" > .embulk/embulk.properties
    - name: Show embulk.properties
      run: cat .embulk/embulk.properties
    - name: Make directory
      run: mkdir gem_0.10.26
    - name: Make directory
      run: mkdir gem_0.10.28
    - name: Make directory
      run: mkdir gem_0.10.31
    - name: Download Embulk 0.10.26
      run: curl https://dl.embulk.org/embulk-0.10.26.jar --location --output embulk-0.10.26.jar
    - name: Download Embulk 0.10.28
      run: curl https://dl.embulk.org/embulk-0.10.28.jar --location --output embulk-0.10.28.jar
    - name: Download Embulk 0.10.31
      run: curl https://dl.embulk.org/embulk-0.10.31.jar --location --output embulk-0.10.31.jar
    - name: Mark executable
      run: chmod u+x embulk-0.10.*.jar
    - name: Install msgpack:1.1.0 for Embulk v0.10.26
      run: ./embulk-0.10.26.jar -Xgem_home=gem_0.10.26 gem install msgpack -v 1.1.0
    - name: Install msgpack:1.1.0 for Embulk v0.10.28
      run: ./embulk-0.10.28.jar -Xgem_home=gem_0.10.28 gem install msgpack -v 1.1.0
    - name: Install msgpack:1.1.0 for Embulk v0.10.31
      run: ./embulk-0.10.31.jar -Xgem_home=gem_0.10.31 gem install msgpack -v 1.1.0
    - name: Install embulk.gem:0.10.26
      run: ./embulk-0.10.26.jar -Xgem_home=gem_0.10.26 gem install embulk -v 0.10.26
    - name: Install embulk.gem:0.10.28
      run: ./embulk-0.10.28.jar -Xgem_home=gem_0.10.28 gem install embulk -v 0.10.28
    - name: Install embulk.gem:0.10.31
      run: ./embulk-0.10.31.jar -Xgem_home=gem_0.10.31 gem install embulk -v 0.10.31
    - name: Install built embulk-guess-csv_verify for Embulk v0.10.26
      run: ./embulk-0.10.26.jar -Xgem_home=gem_0.10.26 gem install --local build/gems/embulk-guess-csv_verify-*.gem
    - name: Install built embulk-guess-csv_verify for Embulk v0.10.28
      run: ./embulk-0.10.28.jar -Xgem_home=gem_0.10.28 gem install --local build/gems/embulk-guess-csv_verify-*.gem
    - name: Install built embulk-guess-csv_verify for Embulk v0.10.31
      run: ./embulk-0.10.31.jar -Xgem_home=gem_0.10.31 gem install --local build/gems/embulk-guess-csv_verify-*.gem
    - name: Guess with Embulk v0.10.26
      run: ./embulk-0.10.26.jar -Xgem_home=gem_0.10.26 guess test.yml -o actual.0.10.26.yml
    - run: diff -s actual.0.10.26.yml expected.yml
    - name: Guess with Embulk v0.10.28
      run: ./embulk-0.10.28.jar -Xgem_home=gem_0.10.28 guess test.yml -o actual.0.10.28.yml
    - run: diff -s actual.0.10.28.yml expected.yml
    - name: Guess with Embulk v0.10.31
      run: ./embulk-0.10.31.jar -Xgem_home=gem_0.10.31 guess test.yml -o actual.0.10.31.yml
    - run: diff -s actual.0.10.31.yml expected.yml
